### ISSUE TITLE
Import of pre-release version

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/ps-rule#138]
**Description of the issue**

When running with a pre-release version of PSRule, errors importing the module. However the module is still imported and run.

**Expected behaviour**

Resolve issue parsing pre-release Sem Version string to `Import-Module` cmdlet.

**Error output**

```text
Error: An error occured importing module 'PSRule'.
```

**Action version:**

- Version: **main - pre-v2**

**Comment by ArmaanMcleod** [comment]
@BernieWhite I also ran into this issue when trying to import the specific pre-release version:

```yaml
- name: Run PSRule analysis
  uses: Microsoft/ps-rule@main
  with:
    modules: 'PSRule.Rules.Azure'
    prerelease: true
    version: 2.0.0-B2202017
```

Captured this error output, similar to what you posted:

```
Run Microsoft/ps-rule@main
Run /home/runner/work/_actions/Microsoft/ps-rule/main/powershell.ps1 -InputType 'repository' -InputPath '' -Modules 'PSRule.Rules.Azure' -Source '.ps-rule/' -Baseline '' -Conventions '' -OutputFormat 'None' -OutputPath '' -Path '' -PreRelease 'true' -Version '2.0.0-B2202017'
[info] Installing PSRule: 2.0.0-B2202017

> Checking module: PSRule.Rules.Azure
  - Installing module
  - Using version: 1.12.1
Error: An error occured importing module 'PSRule'.
```
